name: Java CI with Gradle & SonarQube

on:  
  push:  
    branches: [ main, sim3.1 ]  
  pull_request:  
    branches: [ main ]  
  workflow_dispatch:  # Exécution manuelle

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v4  

      - name: Set up JDK 17  
        uses: actions/setup-java@v3  
        with:  
          distribution: 'temurin'  
          java-version: '17'  

      - name: Grant execute permission to Gradle wrapper  
        run: chmod +x gradlew  

      - name: Cache Gradle dependencies  
        uses: actions/cache@v3  
        with:  
          path: ~/.gradle  
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}  
          restore-keys: gradle-  

      # - name: Build project  
      #   run: ./gradlew build  

      - name: List contents of sonar-application directory
        run: ls -la sonar-application

      - name: Grant execute permission to sonar.sh
        run: chmod +x sonar-application/sonarqube-25.2-SNAPSHOT/bin/linux-x86-64/sonar.sh

      - name: Start SonarQube  
        run: sonar-application/sonarqube-25.2-SNAPSHOT/bin/linux-x86-64/sonar.sh start